.\" 20120318
.TH "gegl" "1" "March 18, 2012"
.SH "NAME"
gegl \- Generic Graphics Library Test Program
.SH "DESCRIPTION"
.B GEGL
is a graph based image processing  framework. GEGLs original design was made to scratch GIMPs itches for a new compositing and processing core. This core is being designed to have minimal dependencies and a simple well defined API.
.PP
.SH "AUTHORS"
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>,
