.TH QPXTOOL 1 "2007-12-27" "0.6.1" "CD/DVD quality checker"

.SH NAME
qpxtool \- CD/DVD quality checker

.SH SYNOPSIS
\fBqpxtool\fR

.SH DESCRIPTION
qpxtool gives you access to all available Quality Checks (Q-Checks) on written and blank media, that are available for your drive. This will help you to find the right media and the optimized writing speed for your hardware, which will increase the change for a long data lifetime.
.PP
qpxtool depends on the used drive, not all drives are able to read the Q-Checks and not all of them are supported by QPxTool. Currently, most newer drives of LiteOn, NEC, Pioneer and Plextor are supported.
.PP

.SH OPTIONS
qpxtool has no options.

.SH SEE ALSO
.PP
\fIpxcontrol\fR(1)
.PP
Homepage: <\fIhttp://qpxtool.sourceforge.net/\fR>

.SH AUTHOR
qpxtool was written by Gennady "ShultZ" Kozlov <qpxtool@mail.ru>.
.PP
This manual page was written by Daniel Baumann <daniel@debian.org>, for the Debian project (but may be used by others).
