.TH compiz-boxmenu 1 "February 2012"
.SH NAME
compizboxmenu \- desktop menu for compiz
.SH DESCRIPTION
compizboxmenu is a desktop menu for compiz, forked from compiz-deskmenu  by crdlb.  Introduces extensive icon support, pipeitems, recent documents  list,  and more!
.SH AUTHORS
Sapphira Armageddos
.SH OTHER
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>
.BR
