.TH DEADBEEF 1 "16 May 2011" "0.5.0" "deadbeef manual page"
.SH NAME
deadbeef \- ultimate music player for X.
.SH SYNOPSIS
.B deadbeef
[\fIOptions\fR] [\fIFiles\fR]
.SH DESCRIPTION
\fIDeadbeef\fP DeaDBeeF (as in 0xDEADBEEF) is an audio player for GNU/Linux
systems with X11.
.SH OPTIONS
.SS "Arguments:"
.TP
File(s)
file(s) to open
.SS "Options:"
.TP
.BI \-h,\-\-help
Show help about options
.TP
.BI \-\-play
Start playback
.TP
.BI \-\-stop
Stop playback
.TP
.BI \-\-pause
Pause playback
.TP
.BI \-\-toggle-pause
Toggle pause
.TP
.BI \-\-play-pause
Start playback if stopped, toggle pause otherwise
.TP
.BI \-\-next
Next song in playlist
.TP
.BI \-\-prev
Previous song in playlist
.TP
.BI \-\-random
Random song in playlist
.TP
.BI \-\-queue
Append file(s) to existing playlist
.TP
.BI \-\-version
Print version info and exit
.TP
.BI \-\-nowplaying\ \fIFMT\fR
Print formatted track name to stdout FMT %-syntax: [a]rtist, [t]itle, al[b]um,
[l]ength, track[n]umber, [y]ear, [c]omment, copy[r]ight, [e]lapsed
.SH "AUTHOR"
DeaDBeeF was written by
.nh
.ad l
Alexey Yakovenko <waker@users.sourceforge.net>
.hy
.br
This manual page was prepared by
.nh
.ad l
Alexey Smirnov <alexey.smirnov@gmx.com>
.hy
for the Debian GNU/Linux system (but may be used by others).
