.\" 20100128
.TH "pytyle" "1" "February 7, 2010"
.SH "NAME"
pytyle \- A manual tiling manager for EWMH compliant window managers 
.SH "DESCRIPTION"
.B pytyle
is an extremely versatile and extensible tiling manager that is meant to be embedded into EWMH window managers. Its feature set was modeled afterthe basic tiling features of XMonad- even down to the key bindings.

It has been tested relatively well on OpenBox and partially on Fluxbox. It should, in theory, work with any window manager complying with the EWMH standards.
.PP
.SH "FILES"
    ~/.config/pytyle/pytylerc - The configuration file for\fB pytyle\fR
.SH "AUTHORS"
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>,
