.\" 20121028
.TH "qt-box-editor" "1" "February 10, 2012"
.SH "NAME"
qt-box-editor \- Tool for adjusting tesseract-ocr box files 
.SH "DESCRIPTION"
.B QT Box Editor
is tool for adjusting tesseract-ocr box files. Aim of this project is to provide easy and efficient way for editing regardles file size.
.PP
.SH "AUTHORS"
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>,
