.\" 20100210
.TH "zNotes" "1" "February 10, 2010"
.SH "NAME"
znotes \- simple lightweight application for notes
.SH "DESCRIPTION"
.B zNotes
provides you a simple text editor in a little  window for the desktop. Notes are especially useful for  temporary stuff. Written in the C++ programming language  using Qt framework.
.PP
.SH "AUTHORS"
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>,
