.TH aegisub-2.1 1 "April 7, 2010"
.SH "NAME"
aegisub-2.1 \- Advance subtitle editor
.SH "SYNOPSIS"
.B aegisub-2.1
.IR "files" "..."
.SH "DESCRIPTION"
Adcanced graphical subtitle editor aming to have full support for Advance
Substation Alpha (.ass) file format. Also support scripting in LUA for
automation of common or repedeteive tasks.
.SH "AUTHOR"
The Aegisub Project <http://www.aegisub.org/>

This manual page was written by Rickard Närström <rickard.narstrom@gmail.com> for Ubuntu Linux.
.SH "SEE ALSO"
API documentation and examples for automation scripts is available in:
.RS
.I /usr/share/doc/aegisub/2.1
.RE
