.TH aegisub-3.2 1 "March 17, 2012"
.SH NAME
aegisub-3.2 \- advanced subtitle editor
.SH SYNOPSIS
.B aegisub-3.2
.IR "files" "..."
.SH DESCRIPTION
Originally created as tool to make typesetting, particularly in anime
fansubs, a less painful experience, Aegisub has grown into a fully
fledged, highly customizable subtitle editor.
.PP
It features a lot of convenient tools to help you with timing, typesetting,
editing and translating subtitles, as well as a powerful scripting environment
called Automation (originally mostly intended for creating karaoke effects,
Automation can now be used much else, including creating macros and various
other convenient tools).
.SH SEE ALSO
You can find more documentation on the following website:
http://docs.aegisub.org/manual/
.SH AUTHOR
aegisub-3.2 was written by the Aegisub Project <http://www.aegisub.org/>.
.PP
This manual page was written by Sebastian Reichel <sre@debian.org>
for the Debian project (but may be used by others).
