debian/gimp.xpm usr/share/pixmaps/
debian/tmp/usr/bin/gimp
debian/tmp/usr/bin/gimp-?.?
debian/tmp/usr/bin/gimp-console
debian/tmp/usr/bin/gimp-console-?.?
debian/tmp/usr/lib/gimp/2.0/environ/
debian/tmp/usr/lib/gimp/2.0/modules/
debian/tmp/usr/lib/gimp/2.0/interpreters/
debian/tmp/usr/lib/gimp/2.0/plug-ins/
debian/tmp/usr/lib/gimp/2.0/python/
debian/tmp/usr/share/applications
debian/tmp/usr/share/man/man1/gimp.1
debian/tmp/usr/share/man/man1/gimp-?.?.1
debian/tmp/usr/share/man/man1/gimp-console.1
debian/tmp/usr/share/man/man1/gimp-console-?.?.1

