.TH UGET-GTK-1TO2 "1" "July 2015" "uget-gtk-1to2 1.10.5" "User Commands"
.SH NAME
uget-gtk-1to2 \- Convert uGet for GTK+ data file from 1.10.x to 2.x
.SH SYNOPSIS
uget-gtk-1to2
[ config  directory ]
.SH EXAMPLES
uget-gtk-1to2  \*(lq/home/your_user/.config/uGet\*(rq
.SH AUTHOR
\fBuget-gtk-1to2\fR was written by Raymond Huang <plushuang at users.sourceforge.net>.
.PP
This manual page was written by Elías Alejandro Año Mendoza <ealmdz@gmail.com>,
for the Debian project (and may be used by others).
