.TH "quneiform" "1" "25 Mar 2012"
.SH "NAME"
quneiform \- graphical interface for cuneiform
.SH "SYNOPSIS"
.PP
.B quneiform
.br
.B quneiform
<file>
.SH "DESCRIPTION"
.B quneiform
is a graphical interface for cuneiform text recognition tools on
the Linux platform. With quneiform you can perform images preprocessing and recognize texts using cuneiform
from a single command centre. quneiform also makes it easy to recognize
several images sequentially.
.SH "COMMAND LINE OPTIONS"
.RB "There is no any command-line option yet."
.PP
.SH AUTHOR
This program was written by Serge Poltavski <serge.poltavski@gmail.com>.
.br
quneiform homepage: \fBhttps://github.com/uliss/quneiform\fR
.SH "BUG REPORTS"
If you find a bug in quneiform please report it here:
.B https://github.com/uliss/quneiform/issues
.PP
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>
