.\" 20100210
.TH "sz1" "1" "February 10, 2010"
.SH "NAME"
 SZ81 \- Sinclair ZX80/ZX81 emulator
.SH "DESCRIPTION"
.B SZ81
is a Sinclair ZX80/ZX81 emulator very much based  upon the work of Ian Collier's xz80 and Russell Marks's  z81 but employing the highly portable SDL and including  additional functionality and features for desktop  computers and portable devices.
.PP
.SH "AUTHORS"
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>,
