.TH "qwit" "1"
.if n .ad l
.nh

.SH "NAME"
qwit \- QT twitter client

.SH "SYNOPSIS"
.B qwit
.RI [ Qt-options ]
.RI [ KDE-options ] 
\&...

.SH "DESCRIPTION"
qwit is a QT twitter client

.SH OPTIONS
.PP
All KDE and Qt
programs accept a some common command-line options. qwit has no
application-specific options.
.PP

.TP
.BR \-\-`help
Show help about options

.TP
.BR \-\-`help\-qt
Show Qt specific options

.TP 
.BR \-\-`help\-kde
Show KDE specific options

.TP 
.BR \-\-`help\-all
Show all options

.TP
.BR \-\-`author
Show author information

.TP
.BR \-\-`version 
Show version information

.TP
.BR \-\-`license
Show license information

.TP
.BR \-\- 
Indicates end of options

.SH COPYRIGHT
This manual page was written by Steve Stalcup
<vorian@ubuntu.com for the Debian system (but may be used by 
others). Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 3 or any later 
version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses.
