usr/lib/gimpdevel/bin
usr/lib/gimpdevel/lib/gimp
usr/lib/gimpdevel/lib/gegl-0.3/
usr/lib/gimpdevel/lib/babl-0.1/
usr/lib/gimpdevel/share/applications
usr/lib/gimpdevel/share/man/man1/
usr/lib/gimpdevel/lib/lib*.so.*
usr/lib/gimpdevel/lib/girepository-1.0
usr/lib/gimpdevel/lib/libgegl-npd-0.3.so
usr/lib/gimpdevel/lib/libgegl-sc-0.3.so
usr/lib/gimpdevel/lib/gio/
debian/gimp-console-devel.sh /usr/bin
debian/gimp-devel.sh /usr/bin
debian/gimp-devel.desktop /usr/share/applications
