.\" 20100210
.TH "rrip_gui" "1" "February 09, 2010"
.SH "NAME"
rrip_gui \-  audio extraction tool for sampling CDs on gtk2 interface
.SH "DESCRIPTION"
.B rrip_gui
aims to deliver high quality rips from audio  cd's to your computer drive. It tries to do so by ripping  the same track with cdparanoia multiple  times and then  comparing the results. It currently has a gtk2 and  a  command-line interface.
.PP
.SH "AUTHORS"
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>,
