.\" 20100210
.TH "rrip_cli" "1" "February 09, 2010"
.SH "NAME"
rrip_cli \-  audio extraction tool for sampling CDs on curses interface
.SH "DESCRIPTION"
.B rrip_cli
aims to deliver high quality rips from audio  cd's to your computer drive. It tries to do so by ripping  the same track with cdparanoia multiple  times and then  comparing the results. It currently has a gtk2 and  a  command-line interface.
.SH SYNOPSIS
.B rrip_cli
[\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR 
Show this usage statement.
.TP
\fB\-d\fR, \fB\-\-defaults\fR 
Skip questions and rip the disc
.TP
\fB\-c\fR, \fB\-\-configure\fR 
Change configuration settings.
.TP
\fB\-v\fR, \fB\-\-verbose\fR 
Display verbose output.
.TP
\fB\-f\fR, \fB\-\-file\fR  \fIfile\fR
Load configuration settings from file \fIfile\fR.
.TP
\fB\-V\fR, \fB\-\-version\fR 
Show current version of rubyripper.c
.PP
.SH "AUTHORS"
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>,
