.TH clementine-player 1 "February 2010"
.SH NAME
clementine
\- An audio player on Qt4
.SH DESCRIPTION
clementine is a multimedia player based on the amaroK 1.4. There are many media players around these days, true. What's missing from most players is a user interface, that doesn't get in the way of the user.
.SH AUTHORS
David Sansome <me@davidsansome.com>

Christian Muehlhaeuser <chris@chris.de>

Mark Kretschmann <markey@web.de>

Max Howell <max.howell@methylblue.com>

Stanislav Karchebny <berk@upnet.ru>
.SH OTHER
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>

This manual page was written by Alejandro Exojo <suy@badopi.org> for the Debian
system (but may be used by others).
.BR
