Author: Jonathan
Last-Update: 2012-07-31

--- compizboxmenu-1.1.1+git20120207.orig/Makefile
+++ compizboxmenu-1.1.1+git20120207/Makefile
@@ -10,20 +10,20 @@ LDFLAGS_CLIENT := `pkg-config --libs dbu
 all: compiz-boxmenu-daemon compiz-boxmenu compiz-boxmenu-dlist compiz-boxmenu-vplist compiz-boxmenu-wlist
 
 compiz-boxmenu: deskmenu.c deskmenu-common.h
-	$(CC) $(CPPFLAGS_CLIENT) $(CFLAGS) $(LDFLAGS_CLIENT) -o $@ $<
+	$(CC) $(CPPFLAGS_CLIENT) $(CFLAGS) -o $@ $< $(LDFLAGS_CLIENT)
 
 compiz-boxmenu-dlist: deskmenu-documentlist-client.c deskmenu-common.h
-	$(CC) $(CPPFLAGS_CLIENT) $(CFLAGS) $(LDFLAGS_CLIENT) -o $@ $<
+	$(CC) $(CPPFLAGS_CLIENT) $(CFLAGS) -o $@ $< $(LDFLAGS_CLIENT)
 
 compiz-boxmenu-vplist: deskmenu-vplist-client.c deskmenu-common.h
-	$(CC) $(CPPFLAGS_CLIENT) $(CFLAGS) $(LDFLAGS_CLIENT) -o $@ $<
+	$(CC) $(CPPFLAGS_CLIENT) $(CFLAGS) -o $@ $< $(LDFLAGS_CLIENT)
 
 compiz-boxmenu-wlist: deskmenu-windowlist-client.c deskmenu-common.h
-	$(CC) $(CPPFLAGS_CLIENT) $(CFLAGS) $(LDFLAGS_CLIENT) -o $@ $<
+	$(CC) $(CPPFLAGS_CLIENT) $(CFLAGS) -o $@ $< $(LDFLAGS_CLIENT)
 
 compiz-boxmenu-daemon: deskmenu-menu.c deskmenu-wnck.c deskmenu-utils.c deskmenu-utils.h deskmenu-wnck.h deskmenu-glue.h deskmenu-common.h deskmenu-menu.h
 
-	$(CC) $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -o $@ deskmenu-menu.c deskmenu-wnck.c deskmenu-utils.c
+	$(CC) $(CPPFLAGS) $(CFLAGS) -o $@ deskmenu-menu.c deskmenu-wnck.c deskmenu-utils.c  $(LDFLAGS)
 
 deskmenu-glue.h: deskmenu-service.xml
 	dbus-binding-tool --mode=glib-server --prefix=deskmenu --output=$@ $^
