.\" 20100128
.TH "bmpanel2cfg" "1" "January 30, 2010"
.SH "NAME"
bmpanel2cfg \- a preferences manager for BitMap Panel
.SH "DESCRIPTION"
.B bmpanel2cfg
is a small graphical utility which configures the BitMap Panel written in PyGTK and released under the BSD. For more information on bmpanel2 see http://code.google.com/p/bmpanel2/
.PP
.SH "AUTHORS"
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>,
