.TH "Chiaki" "1" 
.SH "NAME" 
chiaki \(em PlayStation remote play client 
.SH "SYNOPSIS" 
.PP 
\fBchiaki\fR [\fB-e \fIthis\fR\fP]  [\fB\-\-example \fIthat\fR\fP]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBchiaki\fR command. 
.PP 
\fBchiaki\fR is a remote play client for PlayStation consoles. 
.SH "OPTIONS" 
.IP "\fB-h\fP           \fB\-\-help\fP         " 10 
Displays help on commandline options. 
.IP "\fB\-\-help-all\fP         " 10 
Displays help including Qt specific options. 
.IP "\fB\-\-registkey <registkey>\fP         " 10 
Uses specified registkey. 
.IP "\fB\-\-morning <morning>\fP         " 10 
Uses specified morning. 
.IP "\fB\-\-fullscreen\fP         " 10 
Start window in fullscreen (only for use with stream command) 
.SH "ARGUMENTS" 
.IP "\fBcommand\fP         " 10 
stream, list 
.IP "\fBnickname\fP         " 10 
Needed for stream command to get credentials for onnecting. Use 'list' to get the nickname. 
.IP "\fBhost\fP         " 10 
Address to connect to (when using the stream command) 
.SH "AUTHOR" 
.PP 
This manual page was written by Bartosz Fenski fenio@debian.org for 
the \fBDebian\fP system (and may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 3 any 
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL-3. 
 
.\" created by instant / docbook-to-man 
