.\" 20100128
.TH "obkey" "1" "February 10, 2010"
.SH "NAME"
obkey \- A key editor for openbox 
.SH "DESCRIPTION"
.B Obkey
is a graphical key editor for the Openbox window manager. Openbox uses XML to store its key preferences, and editing these by hand can quickly become tedious. This utility provides a  convenient method of editing the key in a graphical interface,  while not losing the powerful features of Openbox.
.PP
.SH "AUTHORS"
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>,
