.\" 20100210
.TH "launchy" "1" "February 10, 2010"
.SH "NAME"
obkey \- Open Source Keystroke Launcher
.SH "DESCRIPTION"
.B Obkey
Launchy is a free, cross-platform utility, designed to help you forget about your start menu, the icons on your desktop, and even your file manager.  Launchy indexes the programs in your start menu and can launch your documents, project files, folders, and bookmarks with just a few keystrokes!
.PP
.SH "AUTHORS"
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>,
