usr/lib/gimpgtk3/etc/
usr/lib/gimpgtk3/share/gimp/
usr/lib/gimpgtk3/share/icons/
usr/lib/gimpgtk3/share/locale/
usr/lib/gimpgtk3/share/man/man5/
usr/lib/gimpgtk3/share/vala/
usr/lib/gimpgtk3/share/gir-1.0
debian/icons/16x16/gimp-gtk3.png	/usr/share/icons/hicolor/16x16/apps
debian/icons/22x22/gimp-gtk3.png	/usr/share/icons/hicolor/22x22/apps
debian/icons/24x24/gimp-gtk3.png	/usr/share/icons/hicolor/24x24/apps
debian/icons/32x32/gimp-gtk3.png	/usr/share/icons/hicolor/32x32/apps
debian/icons/48x48/gimp-gtk3.png	/usr/share/icons/hicolor/48x48/apps
debian/icons/64x64/gimp-gtk3.png	/usr/share/icons/hicolor/64x64/apps
debian/icons/128x128/gimp-gtk3.png	/usr/share/icons/hicolor/128x128/apps
