usr/lib/gimpgtk3/bin/gimp-?.??
usr/lib/gimpgtk3/bin/gimp-console-?.??
usr/lib/gimpgtk3/bin/gegl
usr/lib/gimpgtk3/bin/gegl-imgcmp
usr/lib/gimpgtk3/lib/gimp
usr/lib/gimpgtk3/lib/gegl-0.?/
usr/lib/gimpgtk3/lib/babl-0.1/
usr/lib/gimpgtk3/share/applications
usr/lib/gimpgtk3/share/man/man1/gimp-?.??.1.gz
usr/lib/gimpgtk3/lib/lib*.so.*
usr/lib/gimpgtk3/lib/girepository-1.0
usr/lib/gimpgtk3/lib/libgegl-npd-0.?.so
usr/lib/gimpgtk3/lib/libgegl-sc-0.?.so
debian/gimp-console-gtk3.sh /usr/bin
debian/gimp-gtk3.sh /usr/bin
debian/gimp-gtk3.desktop /usr/share/applications
