'\" t
.\"     Title: bmpanel2
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 01/13/2010
.\"    Manual: Bmpanel2 Manual
.\"    Source: Bmpanel 2.1
.\"  Language: English
.\"
.TH "BMPANEL2" "1" "01/13/2010" "Bmpanel 2\&.1" "Bmpanel2 Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bmpanel2 \- X11 NETWM compliant panel (desktop switcher, taskbar, systray, clock, launcher, etc\&.) with themeing capabilities\&.
.SH "SYNOPSIS"
.sp
.nf
\fIbmpanel2\fR [\-h|\-\-help] [\-\-version] [\-\-usage] [\-\-list] [\-\-theme=<theme>]
.fi
.SH "DESCRIPTION"
.sp
BMPanel2 (bitmap panel) is a tiny little bar on the top of the screen or on the bottom\&. It contains different "widgets" \- the pieces of functionality which help user to interact with his desktop\&. Some of the default widgets include:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Taskbar \- A list of tasks (windows) on the current desktop\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Desktop Switcher \- Allows user to choose current desktop\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Systray \- Also known as notification area\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Clock \- No comments\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 5.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  5." 4.2
.\}
Launchbar \- Allows user to run different programs in one click\&.
.RE
.sp
The main goal of this project is to create a simple, lightweight, nice looking, but still useful panel, that will be accompanied with another piece of a really good software \- the Openbox 3\&.
.SH "OPTIONS"
.PP
\-h, \-\-help
.RS 4
Prints short list with following tiny descriptions of all of the options\&.
.RE
.PP
\-\-version
.RS 4
Prints currently installed version of the bmpanel2\&.
.RE
.PP
\-\-usage
.RS 4
Prints the most shortest possible bmpanel2 usage reminder\&.
.RE
.PP
\-\-list
.RS 4
Lists all themes found on known paths for current user\&. Additional info such as theme author name will be printed also\&.
.RE
.PP
\-\-theme=<theme>
.RS 4
Override theme parameter in the config file\&.
.RE
.SH "AUTHORS"
.sp
Code and art:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
nsf <no\&.smile\&.face@gmail\&.com>
.RE
.sp
Noir theme:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Andrew Nayenko <resver@gmail\&.com>
.RE
.sp
A lot of Creative Commons covered theme ports (alduin, auriel, curvy, flora, striped):
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
weakhead (http://weakhead\&.deviantart\&.com)
.RE
