usr/lib/gimpdevel/etc/
usr/lib/gimpdevel/share/gimp/
usr/lib/gimpdevel/share/icons/
#usr/lib/gimpdevel/share/appdata/
usr/lib/gimpdevel/share/locale/
usr/lib/gimpdevel/share/man/man5/
usr/lib/gimpdevel/share/vala/
usr/lib/gimpdevel/share/gir-1.0
usr/lib/gimpdevel/share/mypaint-data/
debian/icons/16x16/gimp-devel.png	/usr/share/icons/hicolor/16x16/apps
debian/icons/22x22/gimp-devel.png	/usr/share/icons/hicolor/22x22/apps
debian/icons/24x24/gimp-devel.png	/usr/share/icons/hicolor/24x24/apps
debian/icons/32x32/gimp-devel.png	/usr/share/icons/hicolor/32x32/apps
debian/icons/48x48/gimp-devel.png	/usr/share/icons/hicolor/48x48/apps
debian/icons/64x64/gimp-devel.png	/usr/share/icons/hicolor/64x64/apps
debian/icons/128x128/gimp-devel.png	/usr/share/icons/hicolor/128x128/apps
