.TH PSI 1 "November  1, 2001"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
psi \- jabber client
.SH SYNOPSIS
.B psi
.SH DESCRIPTION
.B psi 
is a free instant messaging application designed for the Jabber
(XMPP) IM network (including Google Talk). It has full Unicode support, 
and supports most important XMPP features like file transfer, group chat,
encryption etc.
.PP
Psi relies on the qca2 library for its encryption features. Therefore,
it's necessary to install libqca2-plugin-ossl for SSL (client-to-server)
encryption and libqca2-plugin-gnupg for PGP (end-to-end) encryption.
.PP
A tutorial can be found on the web at http://psi-im.org/wiki/Tutorial
.PP
This version build whis webkit
.SH AUTHOR
This manual page was written by Jan Niehusmann <jan@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
