--- azpainter-2.1.6.orig/Makefile.in
+++ azpainter-2.1.6/Makefile.in
@@ -14,7 +14,7 @@ CC := @CC@
 CFLAGS := @CFLAGS@ -pthread -Isrc/include -Imlib/include -I. -DHAVE_CONFIG_H \
  -DPACKAGE_DATA_DIR=\"$(datadir)\"
 LDFLAGS := @LDFLAGS@ -pthread
-LIBS := @LIBS@ -lm
+LIBS := @LIBS@ -lm -lz
 
 TARGET := azpainter
 
