--- azpainter-2.1.6.orig/Makefile.in
+++ azpainter-2.1.6/Makefile.in
@@ -17,7 +17,7 @@
 CC := @CC@
 CFLAGS := @CFLAGS@ -pthread -Isrc/include -Imlk/include -I. -DHAVE_CONFIG_H
 LDFLAGS := @LDFLAGS@ -pthread
-LIBS := @LIBS@ -lm
+LIBS := @LIBS@ -lm -lz
 
 TARGET := azpainter
 
