.TH TANGOGIS 1 "2009-01-20" "0.9.5" "GTK+ mapping and GPS application"

.SH NAME
tangoGIS \- GTK+ mapping and GPS application

.SH SYNOPSIS
\fBtangogis\fR

.SH DESCRIPTION
tangoGIS is a map and GPS application. By default, it uses maps from Openstreetmap.

.SH OPTIONS
tangoGIS has no options.

.SH SEE ALSO
\fIconvert2gpx\fR(1),
\fIconvert2osm\fR(1).

.SH HOMEPAGE
More information about tangoGPS can be found at <\fIhttp://www.code.google.com/p/tangogis/\fR>.

.SH AUTHOR
tangoGPS was written by Marcus Bauer <\fImarcus.bauer@gmail.com\fR>.
.PP
This manual page was written by Daniel Baumann <\fIdaniel@debian.org\fR>, for the Debian project (but may be used by others).
