.TH debconf-kde-helper 1 "December 08, 2010"
.SH NAME
debconf-kde-helper \- Provide KDE Debconf frontend
.SH DESCRIPTION
This manual page documents the
.B debconf-kde-helper
command.
.PP
.B debconf-kde-helper
provides a GUI frontend for the Debconf configuration system,
based on the KDE platform libraries.
.PP
.SH OPTIONS
Additional options:
.TP 4
.B \-h, \-\-help
show help about possible commands.
.TP 4
.B \-\-socket-path \fIPATH\fP
Set path to Debconf socket file.
.SH AUTHOR
debconf-kde-helper was written by
Daniel Nicoletti <dantti85-pk@yahoo.com.br>
.PP
This manual page was written by Matthias Klumpp <matthias@nlinux.org>,
for the Debian project (and may be used by others).
