.\" 20170217
.TH "azpainter" "1" "February 16, 2017"
.SH "NAME"
AzPainter \- 16bit RGB full color paint software 
.SH "DESCRIPTION"
.B AzPainter
Full color painting software for Linux for illustration drawing. This is not suitable for dot editing. Since the color is handled with 16 bit color (15 bit fixed point number) internally, the accuracy of color rises, but the memory is consumed correspondingly.
.PP
.SH "AUTHORS"
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>,
