.\" 20100210
.TH "MyRulib" "1" "February 10, 2010"
.SH "NAME"
MyRulib \- Create your own collection of e-books
.SH "DESCRIPTION"
.B MyRulib
is a free (free of charge and with an open source)  program which organizes a home library (collection) of  an e-books in .fb2 format. 
.PP
.SH "AUTHORS"
This manual page was written by Alexander Pozdnyakov <almipo@mail.ru>,
